# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "radiant-page_group_permissions-extension"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Freels", "Nikos Dimitrakopoulos", "Jim Gay", "Matthew Bass", "Andrew vonderLuft"]
  s.date = "2013-02-18"
  s.description = "Enables you to organize users into groups and apply group-based edit permissions to the page hierarchy."
  s.email = "avonderluft@avlux.net"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/groups_controller.rb",
    "app/helpers/groups_helper.rb",
    "app/models/group.rb",
    "app/views/admin/groups/_form.html.haml",
    "app/views/admin/groups/edit.html.haml",
    "app/views/admin/groups/index.html.haml",
    "app/views/admin/groups/new.html.haml",
    "app/views/admin/groups/remove.html.haml",
    "app/views/admin/groups/remove_member.html.haml",
    "app/views/admin/pages/_page_group_form_part.html.haml",
    "app/views/admin/pages/_page_group_td.html.haml",
    "app/views/admin/pages/_page_group_th.html.haml",
    "config/routes.rb",
    "db/migrate/001_create_groups.rb",
    "db/migrate/002_alter_user_columns.rb",
    "lib/controller_extensions.rb",
    "lib/model_extensions.rb",
    "lib/tasks/page_group_permissions_extension_tasks.rake",
    "page_group_permissions_extension.rb",
    "public/images/page_group_permissions/add-member.png",
    "public/images/page_group_permissions/new-group.png",
    "public/images/page_group_permissions/remove-member.png",
    "radiant-page_group_permissions-extension.gemspec",
    "spec/controllers/groups_controller_spec.rb",
    "spec/helpers/groups_helper_spec.rb",
    "spec/models/group_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/avonderluft/radiant-page_group_permissions-extension"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Page Group Permissions Extension for Radiant CMS"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.1"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9.1"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9.1"])
  end
end

